apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    apps.vke.volcengine.com/updated: "2024-02-01T10:17:48Z"
    deployment.kubernetes.io/revision: "11"
  creationTimestamp: "2024-02-01T07:43:13Z"
  generation: 15
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:apps.vke.volcengine.com/updated: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:kubectl.kubernetes.io/restartedAt: {}
            f:labels:
              .: {}
              f:service: {}
          f:spec:
            f:containers:
              k:{"name":"n8n"}:
                .: {}
                f:args: {}
                f:command: {}
                f:env:
                  .: {}
                  k:{"name":"DB_POSTGRESDB_DATABASE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB_POSTGRESDB_HOST"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB_POSTGRESDB_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef: {}
                  k:{"name":"DB_POSTGRESDB_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB_POSTGRESDB_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB_TYPE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"N8N_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"N8N_PROTOCOL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":5678,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/home/node/.n8n"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:initContainers:
              .: {}
              k:{"name":"volume-permissions"}:
                .: {}
                f:command: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/data"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"n8n-claim0"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
    manager: vke-app
    operation: Update
    time: "2024-02-01T10:17:48Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2024-02-01T10:18:00Z"
  name: n8n
  namespace: solution-tools
  resourceVersion: "51565279"
  uid: e3e7e239-0a36-46fc-82e3-7f0433127f3e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-02-01T08:36:42Z"
      creationTimestamp: null
      labels:
        service: n8n
    spec:
      containers:
      - args:
        - -c
        - sleep 5; n8n start
        command:
        - /bin/sh
        env:
        - name: DB_TYPE
          value: postgresdb
        - name: DB_POSTGRESDB_HOST
          value: postgresaf3b8eb4a289.rds-pg.ivolces.com
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        - name: DB_POSTGRESDB_DATABASE
          value: n8n_staging
        - name: DB_POSTGRESDB_USER
          value: n8n_user
        - name: N8N_PROTOCOL
          value: http
        - name: N8N_PORT
          value: "5678"
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: n8n-secret
        image: n8nio/n8n
        imagePullPolicy: Always
        name: n8n
        ports:
        - containerPort: 5678
          protocol: TCP
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/node/.n8n
          name: n8n-claim0
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown 1000:1000 /data
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        name: volume-permissions
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: n8n-claim0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: n8n-claim0
        persistentVolumeClaim:
          claimName: n8n-nfs-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-01T10:18:00Z"
    lastUpdateTime: "2024-02-01T10:18:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-02-01T09:56:16Z"
    lastUpdateTime: "2024-02-01T10:18:00Z"
    message: ReplicaSet "n8n-65f5b5849d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
